webhooks:
  webhooks_enabled:
    client: true
    default: false
  webhooks_url:
    client: true
    default: 'https://example.com/forum-hook'
  webhooks_verify_ssl:
    client: true
    default: true
  webhooks_include_api_key:
    client: true
    default: true
